### ISSUE TITLE
Getting start: python random_predict.py does not work

### ISSUE THREAD

**Issue by onaret** [crowdAI/opensnp-challenge-starter-kit#1]
After running

`pip install -r requirements.txt`

Everything looks fine:

> Requirement already satisfied: appdirs==1.4.3 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: certifi==2017.4.17 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied: click==6.7 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4))
> Requirement already satisfied: crowdai==1.0.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 5))
> Requirement already satisfied: enum-compat==0.0.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6))
> Requirement already satisfied: enum34==1.1.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 7))
> Requirement already satisfied: Flask==0.12.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 8))
> Requirement already satisfied: idna==2.5 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 9))
> Requirement already satisfied: itsdangerous==0.24 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 10))
> Requirement already satisfied: Jinja2==2.9.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 11))
> Requirement already satisfied: MarkupSafe==1.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 12))
> Requirement already satisfied: numpy==1.13.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 13))
> Requirement already satisfied: packaging==16.8 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 14))
> Requirement already satisfied: pyparsing==2.2.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 15))
> Requirement already satisfied: requests==2.18.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 16))
> Requirement already satisfied: scikit-learn==0.18.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 17))
> Requirement already satisfied: scipy==0.19.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 18))
> Requirement already satisfied: six==1.10.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 19))
> Requirement already satisfied: socketIO-client-2==0.7.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 20))
> Requirement already satisfied: termcolor==1.1.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 21))
> Requirement already satisfied: tqdm==4.14.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 22))
> Requirement already satisfied: urllib3==1.21.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 23))
> Requirement already satisfied: websocket-client==0.44.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 24))
> Requirement already satisfied: Werkzeug==0.12.2 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 25))

Then,
`pip install -U crowdai`

Everything looks fine:

> Requirement already up-to-date: crowdai in /usr/lib/python3.6/site-packages
> Requirement already up-to-date: enum-compat>=0.0.2 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: Flask>=0.12.1 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: itsdangerous>=0.24 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: pyparsing>=2.2.0 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: tqdm>=4.11.2 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: six>=1.10.0 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: termcolor>=1.1.0 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: websocket-client>=0.40.0 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: Werkzeug>=0.12.1 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: socketIO-client-2>=0.7.4 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: MarkupSafe>=1.0 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: appdirs>=1.4.3 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: enum34>=1.1.6 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: requests>=2.14.1 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: Jinja2>=2.9.6 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: click>=6.7 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: packaging>=16.8 in /usr/lib/python3.6/site-packages (from crowdai)
> Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests>=2.14.1->crowdai)
> Requirement already up-to-date: idna<2.6,>=2.5 in /usr/lib/python3.6/site-packages (from requests>=2.14.1->crowdai)
> Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.14.1->crowdai)

When running random_predict as follow
`python random_predict.py --api-key=SECRET`

I got this error: 

> Traceback (most recent call last):
>   File "random_predict.py", line 3, in <module>
>     import crowdai
>   File "/usr/lib/python3.6/site-packages/crowdai/__init__.py", line 1, in <module>
>     from .config import config
>   File "/usr/lib/python3.6/site-packages/crowdai/config.py", line 1, in <module>
>     from challenges.opensnp_challenge_2017 import OpenSNPChallenge2017
> ModuleNotFoundError: No module named 'challenges'

**Comment by spMohanty** [comment]
The reason was @onaret was using `python3.6`.
And support for `python3` is yet to be implemented.
Reference issue : https://github.com/crowdAI/opensnp-challenge-starter-kit/issues/2
